export const archiveObjects = [
  {
    id: 'about',
    folio: 'A.01',
    label: 'About Chloe',
    zh: '关于小悦',
    description: '身份、方向与一份持续修改的自述。',
    href: '/about',
    type: 'paper',
    x: '35%',
    y: '14%',
    w: '28%',
    rotate: '1.8deg',
    z: 8,
    title: '小悦 / CHLOE',
    subtitle: 'WHO I AM / 关于我',
    lines: ['小悦 / Chloe', 'Products · Systems · Models', 'Learning in public', 'Independent web']
  },
  {
    id: 'blog',
    folio: 'N.001',
    label: 'Notes',
    zh: '学习笔记',
    description: '把学习过程写成以后仍能查阅的材料。',
    href: '/blog',
    type: 'paper',
    x: '13%',
    y: '38%',
    w: '31%',
    rotate: '-3.8deg',
    z: 7,
    title: 'NOTES / 笔记',
    subtitle: 'WRITTEN ARCHIVE',
    lines: ['Java Notes', 'HTTP Basics', 'SQL Injection', 'XSS', 'Deserialization']
  },
  {
    id: 'projects',
    folio: 'W.01',
    label: 'Work Index',
    zh: '作品索引',
    description: '产品、系统与真实输出的入口。',
    href: '/work',
    type: 'folder',
    x: '48%',
    y: '26%',
    w: '35%',
    rotate: '-1.5deg',
    z: 4,
    title: 'WORK INDEX',
    subtitle: 'PRODUCTS / SYSTEMS',
    lines: ['Enterprise RAG', 'Agent Runtime', 'Product experiments', 'Evidence files']
  },
  {
    id: 'garden',
    folio: 'A.02',
    label: 'Digital Garden',
    zh: '数字花园',
    description: '主题之间的连接，以及仍在生长的知识。',
    href: '/digital-garden',
    type: 'glass',
    x: '58%',
    y: '49%',
    w: '29%',
    rotate: '4.5deg',
    z: 9,
    title: 'DIGITAL GARDEN',
    subtitle: 'GROWING INDEX / 生长中',
    lines: ['Computer Network', 'Database', 'Operating System', 'Algorithms']
  },
  {
    id: 'media',
    folio: 'A.03',
    label: 'Media Diary',
    zh: '阅读与观看',
    description: '书、课程、影像和参考资料留下的索引。',
    href: '/media-diary',
    type: 'photo',
    x: '7%',
    y: '12%',
    w: '25%',
    rotate: '-2deg',
    z: 5,
    title: 'MEDIA DIARY',
    subtitle: 'READING / WATCHING',
    lines: ['Courses', 'Books', 'Videos', 'References']
  },
  {
    id: 'sketchbook',
    folio: 'A.04',
    label: 'Sketchbook',
    zh: '草图本',
    description: '没有被包装成结论的小想法与视觉草稿。',
    href: '/sketchbook',
    type: 'small',
    x: '69%',
    y: '70%',
    w: '19%',
    rotate: '-3deg',
    z: 11,
    title: 'SKETCHBOOK',
    subtitle: 'VISUAL NOTES / 草图',
    lines: ['Tiny ideas', 'Drafts', 'Screenshots']
  },
  {
    id: 'lab',
    folio: 'L.01',
    label: 'Experiment Desk',
    zh: '实验桌',
    description: '模型、运行、评测和失败材料。',
    href: '/lab',
    type: 'paper',
    x: '34%',
    y: '62%',
    w: '25%',
    rotate: '2.8deg',
    z: 10,
    title: '实验桌 / LAB',
    subtitle: 'MODELS / EVALUATION',
    lines: ['Agent runtime', 'Retrieval', 'Failure notes', 'Next experiment']
  }
];

export const menuItems = [
  { href: '/work', label: 'Work' },
  { href: '/lab', label: 'Lab' },
  { href: '/blog', label: 'Notes' },
  { href: '/digital-garden', label: 'Garden' }
];
