import type { ProjectEntry } from '@/components/ProjectTrialIndex';

export const originalProjects = [
  {
    slug: 'remindercat',
    folio: 'W.01',
    name: 'ReminderCat',
    titleZh: '会按时回来找你的提醒喵',
    category: 'PRODUCT / AGENT',
    summary: '把一句自然语言变成提醒事项、持久化调度与到时通知；站内版本可以直接设置倒计时并等待弹窗。',
    tags: ['Java 21', 'Spring Boot', 'WeCom', 'Scheduler', 'Browser Demo'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '站内计时与弹窗在浏览器内真实运行；它不连接企业微信。企业微信回调与主动提醒链路来自仓库材料，本轮未复验线上服务。',
    evidenceUrl: 'https://github.com/hey-Chloe/ReminderCat/blob/560f194e06fb97ad280e4d63887ca9d8de085d5f/README.md#演示流程',
    availability: 'DEMO',
    trialUrl: '/work/#remindercat-demo',
    trialLabel: '设一个一分钟提醒',
    repoUrl: 'https://github.com/hey-Chloe/ReminderCat',
    provenance: '站内体验是浏览器适配版；企业微信、数据库与模型凭据仍需要私有环境。',
    featured: true
  },
  {
    slug: 'kai-cloudpay-mobile',
    folio: 'W.02',
    name: 'Zod / KAI CloudPay Mobile',
    titleZh: '算力市场的移动端与履约台',
    category: 'MOBILE / COMPUTE MARKET',
    summary: '围绕 GPU 资源、价格、卡时账本、订单与供应方流程组织的 Expo 移动端、Web 工作台和后端系统。',
    tags: ['Expo', 'React Native', 'Fastify', 'Ledger', 'GPU Inventory'],
    evidenceState: 'WIP',
    evidenceNote: '2026-08-25 实测 health 返回 200、readiness 返回 503；未验收登录、交易与履约闭环，iOS 商店发布仍是 WIP。',
    evidenceUrl: 'https://cloudpay.kai.com/mobile/v1/health',
    availability: 'DEMO',
    trialUrl: '/demos/zod-mobile/',
    trialLabel: '进入移动端浏览器沙箱',
    demoUrl: 'https://cloudpay.kai.com/',
    demoLabel: '打开公共 Web 工作台',
    provenance: '站内是固定演示库存的浏览器沙箱，不是原生 iOS App；线上页面可访问也不等于生产就绪。公开 Fork 记录仍单列在 Learning Forks。',
    featured: true
  },
  {
    slug: 'kai-admin-console',
    folio: 'W.03',
    name: 'KAI Admin Console',
    titleZh: '企业管理后台与权限工作台',
    category: 'PRODUCT / ADMIN',
    summary: '把组织、成员、角色权限、会话、购买与支付回调放进同一套企业管理工作流。',
    tags: ['RBAC', 'Session', 'Organization', 'Idempotency', 'Admin'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '站内静态体验只使用合成数据；修复交付包可本地审阅，完整公开后台当前要求登录，尚未完成生产部署。',
    availability: 'DEMO',
    trialUrl: '/demos/admin-console/',
    trialLabel: '查看合成数据后台',
    provenance: 'canonical 修复包保留原架构与幂等支付处理；当前没有匿名可用的完整后台入口。'
  },
  {
    slug: 'kai-creator-voting',
    folio: 'W.04',
    name: 'KAI Creator / Voting',
    titleZh: '创作挑战、投稿与投票平台',
    category: 'PRODUCT / CREATOR',
    summary: '围绕活动发布、创作者投稿、作品浏览、投票与异常信号组织的一套 Creator 工作流。',
    tags: ['React', 'Cloudflare', 'Creator Workflow', 'Voting', 'Admin'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '2026-08-25 公开旧 baseline 页面返回 200；内容是合成活动数据，投稿、投票与后台写入需要登录。',
    evidenceUrl: 'https://kai-creator-lab.lovely-rook-0792.chatgpt.site/',
    availability: 'LIVE',
    demoUrl: 'https://kai-creator-lab.lovely-rook-0792.chatgpt.site/activity/neon-city',
    demoLabel: '进入霓虹城市活动',
    provenance: '公开页面不是最新本地 Creator-Commerce 分支，也不代表真实商家、用户、奖励或线上业务量。',
    featured: true
  },
  {
    slug: 'kai-commerce-studio',
    folio: 'W.05',
    name: 'KAI Commerce Studio',
    titleZh: 'AI 电商素材生成工作台',
    category: 'PRODUCT / AI COMMERCE',
    summary: '从参考图、平台与品牌约束生成多张商品素材，并处理积分预扣、失败退款与生成供应商切换。',
    tags: ['Node.js', 'Sharp', 'Workers AI', 'Image Generation', 'Transaction'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '站内是 MOCK / NOT REAL AI OUTPUT 的可操作 UI；本地工程与真实 provider 样例存在，正式多用户存储、支付、审核与生产部署仍未完成。',
    availability: 'DEMO',
    trialUrl: '/demos/kai-commerce/',
    trialLabel: '操作 Mock 工作台',
    provenance: '当前以本地产品闭环展示；没有公开长期在线服务，也不把 mock 输出写成真实 AI 生成。'
  },
  {
    slug: 'kai-play',
    folio: 'W.06',
    name: 'KAI Play',
    titleZh: '卡时体系里的多端小游戏',
    category: 'PRODUCT / GAME',
    summary: '把轻量游戏引擎、Web 与 Expo 移动端接进卡时和支付接口，作为 CloudPay 产品族的一个可独立体验子产品。',
    tags: ['TypeScript', 'React Native', 'Expo', 'Game Engine', 'CloudPay'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '站内是单机浏览器训练场；交付包含 Web、Mobile 与工程门禁，历史测试记录本轮未复跑，支付默认关闭且数据仍是本地 JSON。',
    availability: 'DEMO',
    trialUrl: '/demos/kai-play/',
    trialLabel: '进入单机训练场',
    provenance: '它属于 Zod / CloudPay 项目族；单列用于直接体验，不重复宣称为另一套独立平台。'
  },
  {
    slug: 'compute-intelligence',
    folio: 'W.07',
    name: 'KAI Compute Intelligence',
    titleZh: '可解释的算力筛选与排序实验',
    category: 'ALGORITHM / COMPUTE',
    summary: '先按预算、显存、区域等硬约束过滤，再把可靠性、成本与延迟拆开解释，给出候选 Top 3。',
    tags: ['Hard Filter', 'Ranking', 'Explainability', 'LambdaRank', 'Evaluation'],
    evidenceState: 'PROTOTYPE',
    evidenceNote: '站内只使用 synthetic demo inventory，不会创建订单；V2 LambdaRank benchmark 仍在未提交 worktree，不能称为生产学习排序。',
    availability: 'DEMO',
    trialUrl: '/work/algorithm-lab/?tab=compute',
    trialLabel: '调整约束并查看排序',
    provenance: '排序结果是原型交互；真实库存、订单、线上 A/B 与生产接入均未验证。',
    featured: true
  },
  {
    slug: 'kai-market-lab',
    folio: 'W.08',
    name: 'KAI Market Lab',
    titleZh: '订单簿模型训练与验证实验室',
    category: 'RESEARCH / QUANT',
    summary: '统一订单簿数据、标签、序列协议与多模型评测，用诊断结果检查类别坍缩、量化和推理链路。',
    tags: ['PyTorch', 'DeepLOB', 'TLOB', 'MLflow', 'LOB Evaluation'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'TRAIN-VALIDATION ONLY / NO PNL：正式 held-out、盈利与真实交易均未证明，站内也不会发送订单。',
    availability: 'RESEARCH',
    trialUrl: '/demos/market-lab/',
    trialLabel: '查看只读模型审判台',
    provenance: '上游模型架构不归为自研；可归因部分是数据协议、统一评测、门禁、诊断与 Dashboard。',
    featured: true
  },
  {
    slug: 'budgetagent',
    folio: 'W.09',
    name: 'BudgetAgent / CVV',
    titleZh: '长程 Agent 的验证预算研究',
    category: 'RESEARCH / AGENT EVAL',
    summary: '固定相同前缀后比较 Sham 与 Forced Gold Repair 分支，研究什么时候验证、记录什么以及如何恢复。',
    tags: ['Counterfactual', 'Reset Replay', 'Evaluation', 'Trace', 'Sealed Holdout'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'Forced Gold 只是 5 个任务上的 preliminary positive control，不证明自主 verifier；真实 E0/CVV 干预尚未完成。',
    availability: 'RESEARCH',
    trialUrl: '/work/algorithm-lab/?tab=budget',
    trialLabel: '比较反事实分支',
    provenance: 'development-only 研究材料；无模型训练、无线上成功率提升，sealed held-out 保持未打开。',
    featured: true
  },
  {
    slug: 'enterprise-agentic-rag',
    folio: 'W.10',
    name: 'Enterprise Agentic RAG',
    titleZh: '企业级可追溯 RAG',
    category: 'ALGORITHM / RAG',
    summary: '企业文档经过层级切块、Dense + BM25、RRF 与重排，生成能够重新指回来源的回答。',
    tags: ['LangGraph', 'Milvus', 'Dense + BM25', 'RRF', 'CrossEncoder'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '站内实验使用固定 prototype corpus 与浏览器检索，不是在线 Milvus / BGE；仓库评测使用确定性合成数据，抽样记录 verified=0。',
    evidenceUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag/blob/c1f5f1ff1737b7deb9baf8345735d39b42635219/benchmarks/retrieval_20260814_133802.json',
    availability: 'DEMO',
    trialUrl: '/work/algorithm-lab/?tab=rag',
    trialLabel: '检索并高亮引用',
    caseUrl: '/work/enterprise-agentic-rag/',
    repoUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag',
    guideUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag#快速开始',
    provenance: '站内是机制原型，完整工程仍需按仓库在本地运行；不宣称真实企业部署。',
    featured: true
  },
  {
    slug: 'vlm-data-selection',
    folio: 'W.11',
    name: 'Data-Efficient Visual Instruction Tuning',
    titleZh: 'VLM 数据选择与 LoRA 预研',
    category: 'RESEARCH / VLM',
    summary: '围绕 Qwen2.5-VL、LoRA / SFT 和可复核数据选择，冻结实验矩阵、基线与评测协议。',
    tags: ['Qwen2.5-VL', 'LoRA', 'SFT', 'Data Selection', 'Pre-registration'],
    evidenceState: 'WIP',
    evidenceNote: 'J10 remote launch pending；J02 remote receipt 仅为 user-reported。训练、checkpoint、benchmark 与消融结果尚不能证明 COINCIDE 优势。',
    availability: 'RESEARCH',
    trialUrl: '/work/algorithm-lab/?tab=vlm',
    trialLabel: '查看预注册实验矩阵',
    provenance: '当前是 Phase 0 研究计划，不是已经完成的模型训练或论文结果。'
  },
  {
    slug: 'thesis-prestudy',
    folio: 'W.12',
    name: 'Undergraduate Thesis Pre-study',
    titleZh: '织物疵点识别毕业论文预研',
    category: 'WIP / RESEARCH DESIGN',
    summary: '为棉平纹坯布疵点识别梳理无监督检测、条件性定位、原图级切分与可行性边界。',
    tags: ['Gabor + OCSVM', 'PaDiM', 'PatchCore', 'Anomaly Detection'],
    evidenceState: 'WIP',
    evidenceNote: '当前只有方案与证据核验，没有下载数据、训练模型或产生指标；题目、资源与实验范围仍待导师确认。',
    availability: 'RESEARCH',
    provenance: '预研设计与团队既有项目分开；不继承或冒充任何尚未归属个人的实验、论文或专利成果。'
  },
  {
    slug: 'ruleforge-sast',
    folio: 'W.13',
    name: 'RuleForge-SAST',
    titleZh: '代码扫描与 Patch 验证',
    category: 'PRODUCT / SECURITY',
    summary: '上传 PHP、Python 或 Java 源码，用 Semgrep 扫描、AI 解释漏洞，再对修复后的 Patch 进行二次验证。',
    tags: ['Semgrep', 'FastAPI', 'Vue 3', 'SAST', 'Patch'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '公开仓库提供真实截图、测试与一分钟功能演示；视频不是托管 Web App。',
    evidenceUrl: 'https://github.com/hey-Chloe/RuleForge-SAST/blob/6f0c3ab5ae3f289d0f47dbd6c9ef94527e4647a0/README.md#在线演示',
    availability: 'VIDEO',
    repoUrl: 'https://github.com/hey-Chloe/RuleForge-SAST',
    demoUrl: 'https://www.bilibili.com/video/BV1YC3Z6EEJC/',
    demoLabel: '观看一分钟演示',
    guideUrl: 'https://github.com/hey-Chloe/RuleForge-SAST#快速开始',
    provenance: 'GitHub 非 Fork 公开仓库；真实演示通过 Bilibili 提供，本地前后端按 README 运行。'
  },
  {
    slug: 'miniclaudecode',
    folio: 'W.14',
    name: 'MiniClaudeCode',
    titleZh: '可恢复的 Coding Agent Runtime',
    category: 'AGENT / DEVELOPER TOOL',
    summary: '把 Agent Loop、工具调用、权限策略、Local / Docker Runtime、Checkpoint 与 Evaluation 拆成可以检查的运行时。',
    tags: ['Python', 'Tool Calling', 'Policy', 'Checkpoint', 'Evaluation'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '固定版本包含源码、测试与评估材料；公开视频是真实运行演示，不是在线 Coding Agent。',
    evidenceUrl: 'https://github.com/hey-Chloe/MiniClaudeCode/blob/1790a0d2386eaa70801ded6dfd52249055b4c723/README.md',
    availability: 'VIDEO',
    repoUrl: 'https://github.com/hey-Chloe/MiniClaudeCode',
    demoUrl: 'https://www.bilibili.com/video/BV1ZSgj6uEsy/',
    demoLabel: '观看运行演示',
    guideUrl: 'https://github.com/hey-Chloe/MiniClaudeCode#quick-start',
    caseUrl: '/lab/',
    provenance: 'GitHub 非 Fork 公开仓库；不把自建 benchmark 写成外部标准评测。'
  },
  {
    slug: 'mini-runtime-agent',
    folio: 'W.15',
    name: 'mini-Runtime-Agent',
    titleZh: '只用标准库的最小 Agent Runtime',
    category: 'LAB / AGENT RUNTIME',
    summary: '仅用 Python 标准库实现有界 Loop、工具注册、SQLite Session、Context 压缩与 Trace，并提供离线验收脚本。',
    tags: ['Python stdlib', 'SQLite', 'Trace', 'Context', 'Offline Test'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '仓库提供 acceptance_demo.py、测试与限制记录；README 数字本轮未复跑。',
    evidenceUrl: 'https://github.com/hey-Chloe/mini-runtime-agent/blob/a516387b3513823cbabaa9f2dddc6eddc4d4c02c/README.md#九实测结果2026-08-13',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/mini-runtime-agent',
    guideUrl: 'https://github.com/hey-Chloe/mini-runtime-agent#一运行方式',
    provenance: 'GitHub 非 Fork 公开仓库；当前通过本地终端验收脚本试用。'
  },
  {
    slug: 'ctf-agent',
    folio: 'W.16',
    name: 'CTF-Agent',
    titleZh: '面向授权靶场的 CTF Agent',
    category: 'LAB / SECURITY AGENT',
    summary: '用 ReAct、Docker 工具链和 Checkpoint 组织多轮 CTF 分析，只适用于已获授权的题目与靶场。',
    tags: ['ReAct', 'Docker', 'Checkpoint', 'Security Tools'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '公开仓库提供 CLI 与运行说明；当前没有公开视频、测试报告或 Benchmark。',
    evidenceUrl: 'https://github.com/hey-Chloe/ctf-agent/blob/e30ae1e9b0e945b132a33bf458b937916fcef2fe/README.md#4-运行示例',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/ctf-agent',
    guideUrl: 'https://github.com/hey-Chloe/ctf-agent#4-运行示例',
    provenance: 'GitHub 非 Fork 公开仓库；本地运行需要 Docker、模型配置与合法授权环境。'
  },
  {
    slug: 'okr-agent-platform',
    folio: 'W.17',
    name: 'OKR Agent Platform',
    titleZh: '权限节点仍在占位的 OKR Agent',
    category: 'WIP / ENTERPRISE AGENT',
    summary: '用 Intent、Router 和 OKR Tool 组织企业目标问答；Permission 节点当前固定放行，前端仍是预留结构。',
    tags: ['FastAPI', 'PostgreSQL', 'Redis', 'Permission Stub', 'Agent Workflow'],
    evidenceState: 'WIP',
    evidenceNote: '仓库有后端启动与 Demo 问题说明；权限接口固定返回 PASS，尚无真实前端、公开截图或在线 Demo。',
    evidenceUrl: 'https://github.com/hey-Chloe/okr-agent-platform/blob/7a9b7c3bc4de14c155ef96c0bdb1442a6d731d0e/README.md#demo问题',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/okr-agent-platform',
    guideUrl: 'https://github.com/hey-Chloe/okr-agent-platform#启动',
    provenance: 'GitHub 非 Fork 公开仓库；按 WIP 展示，不把权限占位实现写成已落地 RBAC。'
  },
  {
    slug: 'smartcs-rag',
    folio: 'W.18',
    name: 'SmartCS-RAG',
    titleZh: '企业客服 RAG 后端实验',
    category: 'WIP / RAG BACKEND',
    summary: '围绕文档解析、智能切块、Embedding、Qdrant 与知识库管理搭建的后端实验；文档与当前源码状态仍待同步。',
    tags: ['FastAPI', 'PostgreSQL', 'Qdrant', 'Redis', 'Embedding'],
    evidenceState: 'WIP',
    evidenceNote: 'README 仍写 Phase 0，但源码已出现 RAG 模块与测试；在状态说明同步前只开放技术材料。',
    evidenceUrl: 'https://github.com/hey-Chloe/SmartCS-RAG/blob/c7fe9092446f4ee75b34f315ac65e028b86d9c98/README.md',
    availability: 'SOURCE',
    repoUrl: 'https://github.com/hey-Chloe/SmartCS-RAG',
    guideUrl: 'https://github.com/hey-Chloe/SmartCS-RAG#快速开始',
    provenance: 'GitHub 非 Fork 公开仓库；当前不包装成完整 RAG 产品。'
  },
  {
    slug: 'chloe-notebook',
    folio: 'W.19',
    name: 'Chloe / 我的笔记本',
    titleZh: '早期浏览器笔记本',
    category: 'ARCHIVE / WEB EXPERIMENT',
    summary: '一个能够在浏览器里保存、删除本地笔记，并打开固定 Markdown 笔记的早期网页实验。',
    tags: ['HTML', 'CSS', 'JavaScript', 'localStorage'],
    evidenceState: 'VERIFIED',
    evidenceNote: '2026-08-25 实测 GitHub Pages 返回 200；数据只保存在当前浏览器，没有账户或云同步。',
    evidenceUrl: 'https://github.com/hey-Chloe/Chloe/blob/5b45b6c/index.html',
    availability: 'LIVE',
    repoUrl: 'https://github.com/hey-Chloe/Chloe',
    demoUrl: 'https://hey-chloe.github.io/Chloe/',
    provenance: 'GitHub 非 Fork 公开仓库；作为早期个人网页档案展示，不包装成成熟产品。'
  }
] as const satisfies readonly ProjectEntry[];

export const productProjects = originalProjects.slice(0, 6);
export const researchProjects = originalProjects.slice(6, 12);
export const systemProjects = originalProjects.slice(12, 19);

export const learningForks = [
  {
    slug: 'xiaoyue-ai-portfolio',
    folio: 'F.01',
    name: 'xiaoyue-ai-portfolio',
    titleZh: '3D 作品集改造实验',
    category: 'FORK / DESIGN ITERATION',
    summary: '在 CodeBucks 的 Next.js 3D Portfolio 模板上做内容、路由和视觉改造，用于比较另一种作品集表达。',
    tags: ['Next.js', 'Three.js', 'Tailwind CSS', 'Template Study'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub 显示相对上游 ahead 10 commits；当前公开 Pages 可访问，但底层模板并非原创。',
    evidenceUrl: 'https://github.com/codebucks27/Next.js-Creative-Portfolio-Website/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/xiaoyue-ai-portfolio',
    demoUrl: 'https://hey-chloe.github.io/xiaoyue-ai-portfolio/',
    demoLabel: '查看改造版本',
    provenance: '上游：codebucks27/Next.js-Creative-Portfolio-Website；展示的是改造与学习过程。'
  },
  {
    slug: 'all-in-rag',
    folio: 'F.02',
    name: 'all-in-rag',
    titleZh: 'RAG 全栈教程镜像',
    category: 'FORK / LEARNING RESOURCE',
    summary: 'Datawhale 的 RAG 全栈教程镜像，用于阅读和学习；当前 Fork 与上游完全一致。',
    tags: ['RAG', 'Tutorial', 'Datawhale'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub Compare 为 0 ahead / 0 behind；内容和在线书均属于上游项目。',
    evidenceUrl: 'https://github.com/datawhalechina/all-in-rag/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/all-in-rag',
    demoUrl: 'https://datawhalechina.github.io/all-in-rag/',
    demoLabel: '阅读上游在线书',
    provenance: '上游：datawhalechina/all-in-rag；不作为小悦的原创 Work。'
  },
  {
    slug: 'zod',
    folio: 'F.03',
    name: 'zod / KAI CloudPay mobile',
    titleZh: '移动端工程学习 Fork',
    category: 'FORK / MOBILE',
    summary: '用于检查移动端算力市场工程结构的 Fork；当前没有属于 Chloe 的独立提交或可归因 Demo。',
    tags: ['React Native', 'Android', 'Contract Verification'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub Compare 为 0 ahead / 10 behind；上游产品和线上站点不能归为本人作品。',
    evidenceUrl: 'https://github.com/mandow123/zod/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/zod',
    guideUrl: 'https://github.com/hey-Chloe/zod#本地运行',
    provenance: '上游：mandow123/zod；仅作为学习 Fork 记录。'
  }
] as const satisfies readonly ProjectEntry[];
