import type { ProjectEntry } from '@/components/ProjectTrialIndex';

export const originalProjects = [
  {
    slug: 'enterprise-agentic-rag',
    folio: 'W.01',
    name: 'Enterprise Agentic RAG',
    titleZh: '企业级可追溯 RAG',
    category: 'AGENT / RAG',
    summary: '企业文档经过层级切块、Dense + BM25、RRF、重排和 LangGraph，生成能重新指回来源的回答。',
    tags: ['LangGraph', 'Milvus', 'Dense + BM25', 'RRF', 'CrossEncoder'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '固定仓库含评测报告；本次未复跑。报告使用确定性生成数据集，抽样记录 verified=0。',
    evidenceUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag/blob/c1f5f1ff1737b7deb9baf8345735d39b42635219/benchmarks/retrieval_20260814_133802.json',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag',
    guideUrl: 'https://github.com/hey-Chloe/enterprise-agentic-rag#快速开始',
    caseUrl: '/work/enterprise-agentic-rag/',
    provenance: 'GitHub 非 Fork 公开仓库；当前没有公开 Web Demo，站内案例只展示可追溯的仓库材料。',
    featured: true
  },
  {
    slug: 'ruleforge-sast',
    folio: 'W.02',
    name: 'RuleForge-SAST',
    titleZh: '代码扫描与 Patch 验证',
    category: 'PRODUCT / SECURITY',
    summary: '上传 PHP、Python 或 Java 源码，用 Semgrep 扫描、AI 解释漏洞，再对修复后的 Patch 进行二次验证。',
    tags: ['Semgrep', 'FastAPI', 'Vue 3', 'SAST', 'Patch'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '公开仓库提供真实截图、测试与一分钟功能演示；视频不是托管 Web App。',
    evidenceUrl: 'https://github.com/hey-Chloe/RuleForge-SAST/blob/6f0c3ab5ae3f289d0f47dbd6c9ef94527e4647a0/README.md#在线演示',
    availability: 'VIDEO',
    repoUrl: 'https://github.com/hey-Chloe/RuleForge-SAST',
    demoUrl: 'https://www.bilibili.com/video/BV1YC3Z6EEJC/',
    demoLabel: '观看一分钟演示',
    guideUrl: 'https://github.com/hey-Chloe/RuleForge-SAST#快速开始',
    provenance: 'GitHub 非 Fork 公开仓库；真实演示通过 Bilibili 提供，本地前后端按 README 运行。',
    featured: true
  },
  {
    slug: 'miniclaudecode',
    folio: 'W.03',
    name: 'MiniClaudeCode',
    titleZh: '可恢复的 Coding Agent Runtime',
    category: 'AGENT / DEVELOPER TOOL',
    summary: '把 Agent Loop、工具调用、权限策略、Local / Docker Runtime、Checkpoint 与 Evaluation 拆成可以检查的运行时。',
    tags: ['Python', 'Tool Calling', 'Policy', 'Checkpoint', 'Evaluation'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '固定版本包含源码、测试与评估材料；站内 Lab 是静态机制检查，本次没有重跑 Agent。',
    evidenceUrl: 'https://github.com/hey-Chloe/MiniClaudeCode/blob/1790a0d2386eaa70801ded6dfd52249055b4c723/README.md',
    availability: 'VIDEO',
    repoUrl: 'https://github.com/hey-Chloe/MiniClaudeCode',
    demoUrl: 'https://www.bilibili.com/video/BV1ZSgj6uEsy/',
    demoLabel: '观看运行演示',
    guideUrl: 'https://github.com/hey-Chloe/MiniClaudeCode#quick-start',
    caseUrl: '/lab/',
    provenance: 'GitHub 非 Fork 公开仓库；公开视频是真实演示，不是在线沙箱。',
    featured: true
  },
  {
    slug: 'remindercat',
    folio: 'W.04',
    name: 'ReminderCat',
    titleZh: '企业微信自然语言提醒助手',
    category: 'PRODUCT / AGENT',
    summary: '把企业微信回调、自然语言意图、持久化调度和主动提醒连成一条完整链路。',
    tags: ['Java 21', 'Spring Boot', 'WeCom', 'Scheduler', 'PostgreSQL'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'README 记录手机验收与演示流程；当前没有公开端点或脱敏录屏，试用需要企业微信与模型凭据。',
    evidenceUrl: 'https://github.com/hey-Chloe/ReminderCat/blob/560f194e06fb97ad280e4d63887ca9d8de085d5f/README.md#演示流程',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/ReminderCat',
    guideUrl: 'https://github.com/hey-Chloe/ReminderCat#本地运行',
    provenance: 'GitHub 非 Fork 公开仓库；展示为本地与私有集成项目，不宣称存在公开在线服务。'
  },
  {
    slug: 'mini-runtime-agent',
    folio: 'L.02',
    name: 'mini-Runtime-Agent',
    titleZh: '只用标准库的最小 Agent Runtime',
    category: 'LAB / AGENT RUNTIME',
    summary: '仅用 Python 标准库实现有界 Loop、工具注册、SQLite Session、Context 压缩与 Trace，并提供离线验收脚本。',
    tags: ['Python stdlib', 'SQLite', 'Trace', 'Context', 'Offline Test'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '仓库提供 acceptance_demo.py、测试与限制记录；README 数字本次未复跑。',
    evidenceUrl: 'https://github.com/hey-Chloe/mini-runtime-agent/blob/a516387b3513823cbabaa9f2dddc6eddc4d4c02c/README.md#九实测结果2026-08-13',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/mini-runtime-agent',
    guideUrl: 'https://github.com/hey-Chloe/mini-runtime-agent#一运行方式',
    provenance: 'GitHub 非 Fork 公开仓库；当前通过本地终端验收脚本试用。'
  },
  {
    slug: 'ctf-agent',
    folio: 'L.03',
    name: 'CTF-Agent',
    titleZh: '面向授权靶场的 CTF Agent',
    category: 'LAB / SECURITY AGENT',
    summary: '用 ReAct、Docker 工具链和 Checkpoint 组织多轮 CTF 分析，只适用于已获授权的题目与靶场。',
    tags: ['ReAct', 'Docker', 'Checkpoint', 'Security Tools'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: '公开仓库提供 CLI 与运行说明；当前没有公开视频、测试报告或 Benchmark。',
    evidenceUrl: 'https://github.com/hey-Chloe/ctf-agent/blob/e30ae1e9b0e945b132a33bf458b937916fcef2fe/README.md#4-运行示例',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/ctf-agent',
    guideUrl: 'https://github.com/hey-Chloe/ctf-agent#4-运行示例',
    provenance: 'GitHub 非 Fork 公开仓库；本地运行需要 Docker、模型配置与合法授权环境。'
  },
  {
    slug: 'okr-agent-platform',
    folio: 'W.05',
    name: 'OKR Agent Platform',
    titleZh: '权限节点仍在占位的 OKR Agent',
    category: 'WIP / ENTERPRISE AGENT',
    summary: '用 Intent、Router 和 OKR Tool 组织企业目标问答；Permission 节点当前固定放行，前端仍是预留结构。',
    tags: ['FastAPI', 'PostgreSQL', 'Redis', 'Permission Stub', 'Agent Workflow'],
    evidenceState: 'WIP',
    evidenceNote: '仓库有后端启动与 Demo 问题说明；权限接口固定返回 PASS，尚无真实前端、公开截图或在线 Demo。',
    evidenceUrl: 'https://github.com/hey-Chloe/okr-agent-platform/blob/7a9b7c3bc4de14c155ef96c0bdb1442a6d731d0e/README.md#demo问题',
    availability: 'LOCAL',
    repoUrl: 'https://github.com/hey-Chloe/okr-agent-platform',
    guideUrl: 'https://github.com/hey-Chloe/okr-agent-platform#启动',
    provenance: 'GitHub 非 Fork 公开仓库；按 WIP 展示，不把权限占位实现写成已落地 RBAC。'
  },
  {
    slug: 'smartcs-rag',
    folio: 'L.04',
    name: 'SmartCS-RAG',
    titleZh: '企业客服 RAG 后端实验',
    category: 'WIP / RAG BACKEND',
    summary: '围绕文档解析、智能切块、Embedding、Qdrant 与知识库管理搭建的后端实验；文档与当前源码状态仍待同步。',
    tags: ['FastAPI', 'PostgreSQL', 'Qdrant', 'Redis', 'Embedding'],
    evidenceState: 'WIP',
    evidenceNote: 'README 仍写 Phase 0，但源码已出现 RAG 模块与测试；在状态说明同步前只开放源码检查。',
    evidenceUrl: 'https://github.com/hey-Chloe/SmartCS-RAG/blob/c7fe9092446f4ee75b34f315ac65e028b86d9c98/README.md',
    availability: 'SOURCE',
    repoUrl: 'https://github.com/hey-Chloe/SmartCS-RAG',
    guideUrl: 'https://github.com/hey-Chloe/SmartCS-RAG#快速开始',
    provenance: 'GitHub 非 Fork 公开仓库；当前不包装成完整 RAG 产品。'
  },
  {
    slug: 'chloe-notebook',
    folio: 'A.05',
    name: 'Chloe / 我的笔记本',
    titleZh: '早期浏览器笔记本',
    category: 'ARCHIVE / WEB EXPERIMENT',
    summary: '一个能够在浏览器里保存、删除本地笔记，并打开固定 Markdown 笔记的早期网页实验。',
    tags: ['HTML', 'CSS', 'JavaScript', 'localStorage'],
    evidenceState: 'VERIFIED',
    evidenceNote: '2026-08-25 实测 GitHub Pages 返回 200；数据只保存在当前浏览器，没有账户或云同步。',
    evidenceUrl: 'https://github.com/hey-Chloe/Chloe/blob/5b45b6c/index.html',
    availability: 'LIVE',
    repoUrl: 'https://github.com/hey-Chloe/Chloe',
    demoUrl: 'https://hey-chloe.github.io/Chloe/',
    provenance: 'GitHub 非 Fork 公开仓库；作为早期个人网页档案展示，不包装成成熟产品。'
  }
] as const satisfies readonly ProjectEntry[];

export const learningForks = [
  {
    slug: 'xiaoyue-ai-portfolio',
    folio: 'F.01',
    name: 'xiaoyue-ai-portfolio',
    titleZh: '3D 作品集改造实验',
    category: 'FORK / DESIGN ITERATION',
    summary: '在 CodeBucks 的 Next.js 3D Portfolio 模板上做内容、路由和视觉改造，用于比较另一种作品集表达。',
    tags: ['Next.js', 'Three.js', 'Tailwind CSS', 'Template Study'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub 显示相对上游 ahead 10 commits；当前公开 Pages 可访问，但底层模板并非原创。',
    evidenceUrl: 'https://github.com/codebucks27/Next.js-Creative-Portfolio-Website/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/xiaoyue-ai-portfolio',
    demoUrl: 'https://hey-chloe.github.io/xiaoyue-ai-portfolio/',
    demoLabel: '查看改造版本',
    provenance: '上游：codebucks27/Next.js-Creative-Portfolio-Website；展示的是改造与学习过程。'
  },
  {
    slug: 'all-in-rag',
    folio: 'F.02',
    name: 'all-in-rag',
    titleZh: 'RAG 全栈教程镜像',
    category: 'FORK / LEARNING RESOURCE',
    summary: 'Datawhale 的 RAG 全栈教程镜像，用于阅读和学习；当前 Fork 与上游完全一致。',
    tags: ['RAG', 'Tutorial', 'Datawhale'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub Compare 为 0 ahead / 0 behind；内容和在线书均属于上游项目。',
    evidenceUrl: 'https://github.com/datawhalechina/all-in-rag/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/all-in-rag',
    demoUrl: 'https://datawhalechina.github.io/all-in-rag/',
    demoLabel: '阅读上游在线书',
    provenance: '上游：datawhalechina/all-in-rag；不作为小悦的原创 Work。'
  },
  {
    slug: 'zod',
    folio: 'F.03',
    name: 'zod / KAI CloudPay mobile',
    titleZh: '移动端工程学习 Fork',
    category: 'FORK / MOBILE',
    summary: '用于检查移动端算力市场工程结构的 Fork；当前没有属于 Chloe 的独立提交或可归因 Demo。',
    tags: ['React Native', 'Android', 'Contract Verification'],
    evidenceState: 'REPOSITORY REPORTED',
    evidenceNote: 'GitHub Compare 为 0 ahead / 10 behind；上游产品和线上站点不能归为本人作品。',
    evidenceUrl: 'https://github.com/mandow123/zod/compare/main...hey-Chloe:main',
    availability: 'FORK',
    repoUrl: 'https://github.com/hey-Chloe/zod',
    guideUrl: 'https://github.com/hey-Chloe/zod#本地运行',
    provenance: '上游：mandow123/zod；仅作为学习 Fork 记录。'
  }
] as const satisfies readonly ProjectEntry[];
