export type Locale = "zh" | "en";

/** Locale prefixes apply to page routes, never public assets or external URLs. */
export function localePath(path: string, locale: Locale): string {
  if (!path.startsWith("/") || path.startsWith("//")) return path;
  const [, pathname, suffix = ""] = path.match(/^([^?#]*)([?#].*)?$/) || [];
  const root = pathname === "/en" ? "/" : pathname.startsWith("/en/") ? pathname.slice(3) : pathname;
  return `${locale === "en" ? `/en${root}` : root}${suffix}`;
}
export function contentHref(href: string, locale: Locale): string {
  return /^\/(?:$|[?#]|(?:research|publications|experience|projects|writing|cv)(?:\/|$|[?#]))/.test(href) ? localePath(href, locale) : href;
}
const en = {
  resultFigure: "Experimental results from the public project materials. Scroll horizontally on small screens.", researchTopics: "LLM · Multimodal · Agent · Evaluation", research: "Research", selectedResearch: "Selected Research", publications: "Publications", experience: "Experience", projects: "Projects", writing: "Research Notes", cv: "CV", biography: "Biography", engineering: "Engineering", openSource: "Open Source", industry: "Research & Industry", interests: "Research interests", home: "Home", menu: "Menu", close: "Close", navigation: "Main navigation", skip: "Skip to content", backTop: "Back to top", allResearch: "All research", allContributions: "All contributions", allProjects: "All projects", allWriting: "All writing", fullList: "Full list", viewAll: "View all", researchQuestion: "Research question", method: "Method", keyResults: "Key results", problem: "Problem", ownership: "Ownership", scale: "Scale", result: "Result", outcome: "Outcome", contribution: "Contribution", present: "Present", unavailable: "Not yet available", toAdd: "To be added", dateToAdd: "Dates to be added", paper: "Paper", code: "Code", dataset: "Dataset", demo: "Demo", project: "Project page", pullRequest: "Pull request", repository: "Repository", docs: "Documentation", infrastructure: "Infrastructure", archive: "Research archive", forthcoming: "Project details and supporting materials are being prepared.", noPublications: "No publications listed", publicationArchive: "Publication archive", roles: "Roles", publishedNotes: "Published notes", projectsTitle: "Research tools & engineering", projectsDescription: "Open-source contributions, research infrastructure, and engineering projects.", researchEngineering: "Research & Engineering", role: "Research Engineer / AI Engineer", footer: "Research, with evidence.", email: "Email", scholar: "Google Scholar", education: "Education", expected: "Expected graduation", curriculum: "Curriculum vitae", downloadCV: "Download CV", copy: "Copy citation", copied: "Copied", copyFallback: "Select and copy the citation below", minRead: "min read", topics: "Topics", noteMissing: "Note not found", researchMissing: "Research not found", returnHome: "Return home", notFound: "This page is not available.", notFoundDescription: "This address does not lead to a published page.", onThisPage: "On this page", abstract: "Abstract", architecture: "Architecture", experiments: "Experiments", results: "Results", ablation: "Ablation", failureAnalysis: "Failure Analysis", citation: "Citation", originalArticle: "Article in its original language",
} as const;
const zh: Record<keyof typeof en, string> = {
  resultFigure: "基于公开项目材料整理的实验结果；小屏可横向滑动查看。", researchTopics: "大语言模型 · 多模态 · 智能体 · 评估", research: "研究", selectedResearch: "精选研究", publications: "论文", experience: "经历", projects: "项目", writing: "研究笔记", cv: "简历", biography: "关于我", engineering: "工程实践", openSource: "开源贡献", industry: "研究与行业经历", interests: "研究方向", home: "主页", menu: "菜单", close: "关闭", navigation: "主导航", skip: "跳至正文", backTop: "回到顶部", allResearch: "全部研究", allContributions: "全部贡献", allProjects: "全部项目", allWriting: "全部笔记", fullList: "完整列表", viewAll: "查看全部", researchQuestion: "研究问题", method: "方法", keyResults: "主要结果", problem: "问题", ownership: "负责范围", scale: "规模", result: "结果", outcome: "成果", contribution: "具体贡献", present: "至今", unavailable: "资料待补充", toAdd: "待补充", dateToAdd: "日期待补充", paper: "论文", code: "代码", dataset: "数据集", demo: "演示", project: "项目主页", pullRequest: "贡献 PR", repository: "仓库", docs: "文档", infrastructure: "研究基础设施", archive: "研究档案", forthcoming: "项目详情与支持材料整理中。", noPublications: "暂无论文记录", publicationArchive: "论文归档", roles: "任职记录", publishedNotes: "已发布笔记", projectsTitle: "研究工具与工程实践", projectsDescription: "开源贡献、研究基础设施与工程项目。", researchEngineering: "研究与工程", role: "研究工程师 / AI 工程师", footer: "以证据为基础的研究。", email: "邮箱", scholar: "谷歌学术", education: "教育背景", expected: "预计毕业", curriculum: "个人简历", downloadCV: "下载简历", copy: "复制引用", copied: "已复制", copyFallback: "请选择下方引用并手动复制", minRead: "分钟阅读", topics: "主题", noteMissing: "笔记未找到", researchMissing: "研究未找到", returnHome: "返回主页", notFound: "页面暂不存在。", notFoundDescription: "该地址没有已发布的内容。", onThisPage: "本页目录", abstract: "摘要", architecture: "系统架构", experiments: "实验设计", results: "实验结果", ablation: "消融分析", failureAnalysis: "失败分析", citation: "引用", originalArticle: "正文保留原始语言",
};
export function labels(locale: Locale = "zh"): Record<keyof typeof en, string> { return locale === "en" ? en : zh; }
